# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctty < Formula
  desc "A lightweight terminal connection manager for SSH, serial, and SFTP"
  homepage "https://github.com/zsuroy/ctty"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsuroy/ctty/releases/download/v0.6.3/ctty_Darwin_x86_64.tar.gz"
      sha256 "19758aa1899a8548dc58e2738afb66837b01b630c7916544f38fb60683d2451e"

      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsuroy/ctty/releases/download/v0.6.3/ctty_Darwin_arm64.tar.gz"
      sha256 "f2cf3ce80b83aad39b4c7ce6864af4f6ffbc88080e9a1db90cc80ff8f3eda16d"

      define_method(:install) do
        bin.install "ctty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.6.3/ctty_Linux_x86_64.tar.gz"
      sha256 "f87fd7722ca7b6b41d4e9a24c9c459cf93288ca7d69c2b01593c67b9c9695125"
      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.6.3/ctty_Linux_armv6.tar.gz"
      sha256 "bf255640d2c5605200fe982a39df14ce70a93159f70ba2f7ca7cf48e32b28924"
      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.6.3/ctty_Linux_arm64.tar.gz"
      sha256 "521a7105e18a4dfe7ebecb943ab263560e1bf0de70b043782c1ba412e7cb7a03"
      define_method(:install) do
        bin.install "ctty"
      end
    end
  end

  test do
    system "#{bin}/ctty --version"
  end
end
