# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctty < Formula
  desc "A lightweight terminal connection manager for SSH, serial, and SFTP"
  homepage "https://github.com/zsuroy/ctty"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zsuroy/ctty/releases/download/v0.5.1/ctty_Darwin_x86_64.tar.gz"
      sha256 "289e4189b7c597eba6ee5b47e39cd30ebf1fe6dc87f5923c88cddeb156a096fa"

      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zsuroy/ctty/releases/download/v0.5.1/ctty_Darwin_arm64.tar.gz"
      sha256 "a1c9ac7d84b2a4669460036029bb37d6f1036b2ccadb8f49d0bd89d705186a3c"

      define_method(:install) do
        bin.install "ctty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.5.1/ctty_Linux_x86_64.tar.gz"
      sha256 "2b3a8ba424194b205b951ec94a96c26d89c10be0efbc7a9611e714c18a446fbf"
      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.5.1/ctty_Linux_armv6.tar.gz"
      sha256 "1682128000a157e17d7224ed566b1b425b9358a560a2497489248b854fe9d4de"
      define_method(:install) do
        bin.install "ctty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zsuroy/ctty/releases/download/v0.5.1/ctty_Linux_arm64.tar.gz"
      sha256 "308b604f8039eb697b4ccbcaabe633a1cbda97dcf9ec49e44ad28288766d7e18"
      define_method(:install) do
        bin.install "ctty"
      end
    end
  end

  test do
    system "#{bin}/ctty --version"
  end
end
